# Generated by Django 3.2.3 on 2021-05-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='icon',
        ),
    ]
